### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by Mudryi** [apls777/spotty#128]
I have a problem while running `spotty start` in logs there is a problem with the pip install 

RuntimeError: can't start a new thread

I tried to remove the pip install from the Docker file, the container was built successfully, but after that, i got the same problem if connected via Spotty sh and ran any pip command

As i understand this problem potentially happened because of a bad Docker version. Any suggestion on how can i easily change it?

Here is my Docker file 
```
FROM python:3.9

COPY requirements-spotty.txt requirements-spotty.txt

RUN pip3 install -r requirements-spotty.txt
```

And here is my spotty file
```
project:
  name: asr
  syncFilters:
    - exclude:
        - .idea/*
        - .git/*

containers:
  - projectDir: /workspace/project
    file: docker/Dockerfile.spotty
    runtimeParameters: [ '--shm-size', '8G' ]
    volumeMounts:
      - name: workspace
        mountPath: /workspace


instances:
  - name: asr-finetune
    provider: aws
    parameters:
      region: eu-central-1
      instanceType: g4dn.xlarge
      dockerDataRoot: /docker
      volumes:
        - name: workspace
          parameters:
            size: 50
            deletionPolicy: retain
        - name: docker
          parameters:
            size: 50
            mountDir: /docker
            deletionPolicy: retain

scripts:
  train: |
    python main.py

```
